# Generated by Django 4.2.7 on 2025-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='slmc_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
