# Generated by Django 5.2 on 2025-04-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='district',
        ),
    ]
